// Code generated by protoc-gen-go.
// source: configData.proto
// DO NOT EDIT!

/*
Package configdata is a generated protocol buffer package.

It is generated from these files:
	configData.proto

It has these top-level messages:
	Job
	CodeManager
	BuildManager
	Git
	Repo
	GitAdvanced
	Ant
	Maven
*/
package configdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CodeManager_Kind int32

const (
	CodeManager_NONE CodeManager_Kind = 0
	CodeManager_GIT  CodeManager_Kind = 1
)

var CodeManager_Kind_name = map[int32]string{
	0: "NONE",
	1: "GIT",
}
var CodeManager_Kind_value = map[string]int32{
	"NONE": 0,
	"GIT":  1,
}

func (x CodeManager_Kind) String() string {
	return proto.EnumName(CodeManager_Kind_name, int32(x))
}
func (CodeManager_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type BuildManager_Kind int32

const (
	BuildManager_NONE BuildManager_Kind = 0
	BuildManager_ANT  BuildManager_Kind = 1
	BuildManager_MVN  BuildManager_Kind = 2
)

var BuildManager_Kind_name = map[int32]string{
	0: "NONE",
	1: "ANT",
	2: "MVN",
}
var BuildManager_Kind_value = map[string]int32{
	"NONE": 0,
	"ANT":  1,
	"MVN":  2,
}

func (x BuildManager_Kind) String() string {
	return proto.EnumName(BuildManager_Kind_name, int32(x))
}
func (BuildManager_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Job struct {
	Id                  string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	NextExecTime        string        `protobuf:"bytes,2,opt,name=nextExecTime" json:"nextExecTime,omitempty"`
	JdkVersion          string        `protobuf:"bytes,3,opt,name=jdkVersion" json:"jdkVersion,omitempty"`
	BuildImgCmd         string        `protobuf:"bytes,4,opt,name=buildImgCmd" json:"buildImgCmd,omitempty"`
	PushImgCmd          string        `protobuf:"bytes,5,opt,name=pushImgCmd" json:"pushImgCmd,omitempty"`
	CurrentNumber       int32         `protobuf:"varint,7,opt,name=currentNumber" json:"currentNumber,omitempty"`
	MaxExecutionRecords int32         `protobuf:"varint,8,opt,name=maxExecutionRecords" json:"maxExecutionRecords,omitempty"`
	MaxKeepDays         int32         `protobuf:"varint,9,opt,name=maxKeepDays" json:"maxKeepDays,omitempty"`
	JobRemoved          int32         `protobuf:"varint,10,opt,name=jobRemoved" json:"jobRemoved,omitempty"`
	CodeManager         *CodeManager  `protobuf:"bytes,11,opt,name=codeManager" json:"codeManager,omitempty"`
	BuildManager        *BuildManager `protobuf:"bytes,12,opt,name=buildManager" json:"buildManager,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetCodeManager() *CodeManager {
	if m != nil {
		return m.CodeManager
	}
	return nil
}

func (m *Job) GetBuildManager() *BuildManager {
	if m != nil {
		return m.BuildManager
	}
	return nil
}

type CodeManager struct {
	Select    CodeManager_Kind `protobuf:"varint,1,opt,name=select,enum=configdata.CodeManager_Kind" json:"select,omitempty"`
	GitConfig *Git             `protobuf:"bytes,2,opt,name=gitConfig" json:"gitConfig,omitempty"`
}

func (m *CodeManager) Reset()                    { *m = CodeManager{} }
func (m *CodeManager) String() string            { return proto.CompactTextString(m) }
func (*CodeManager) ProtoMessage()               {}
func (*CodeManager) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CodeManager) GetGitConfig() *Git {
	if m != nil {
		return m.GitConfig
	}
	return nil
}

type BuildManager struct {
	Select    BuildManager_Kind `protobuf:"varint,1,opt,name=select,enum=configdata.BuildManager_Kind" json:"select,omitempty"`
	AntConfig *Ant              `protobuf:"bytes,2,opt,name=antConfig" json:"antConfig,omitempty"`
	MvnConfig *Maven            `protobuf:"bytes,3,opt,name=mvnConfig" json:"mvnConfig,omitempty"`
}

func (m *BuildManager) Reset()                    { *m = BuildManager{} }
func (m *BuildManager) String() string            { return proto.CompactTextString(m) }
func (*BuildManager) ProtoMessage()               {}
func (*BuildManager) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BuildManager) GetAntConfig() *Ant {
	if m != nil {
		return m.AntConfig
	}
	return nil
}

func (m *BuildManager) GetMvnConfig() *Maven {
	if m != nil {
		return m.MvnConfig
	}
	return nil
}

type Git struct {
	Branch string `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Repo   *Repo  `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
}

func (m *Git) Reset()                    { *m = Git{} }
func (m *Git) String() string            { return proto.CompactTextString(m) }
func (*Git) ProtoMessage()               {}
func (*Git) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Git) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

type Repo struct {
	Url         string       `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Credentials string       `protobuf:"bytes,2,opt,name=credentials" json:"credentials,omitempty"`
	Advanced    *GitAdvanced `protobuf:"bytes,3,opt,name=advanced" json:"advanced,omitempty"`
}

func (m *Repo) Reset()                    { *m = Repo{} }
func (m *Repo) String() string            { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()               {}
func (*Repo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Repo) GetAdvanced() *GitAdvanced {
	if m != nil {
		return m.Advanced
	}
	return nil
}

type GitAdvanced struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Refspec string `protobuf:"bytes,2,opt,name=refspec" json:"refspec,omitempty"`
}

func (m *GitAdvanced) Reset()                    { *m = GitAdvanced{} }
func (m *GitAdvanced) String() string            { return proto.CompactTextString(m) }
func (*GitAdvanced) ProtoMessage()               {}
func (*GitAdvanced) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Ant struct {
	Version    string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Targets    string `protobuf:"bytes,2,opt,name=targets" json:"targets,omitempty"`
	BuildFile  string `protobuf:"bytes,3,opt,name=buildFile" json:"buildFile,omitempty"`
	Properties string `protobuf:"bytes,4,opt,name=properties" json:"properties,omitempty"`
	Javaopts   string `protobuf:"bytes,5,opt,name=javaopts" json:"javaopts,omitempty"`
}

func (m *Ant) Reset()                    { *m = Ant{} }
func (m *Ant) String() string            { return proto.CompactTextString(m) }
func (*Ant) ProtoMessage()               {}
func (*Ant) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Maven struct {
	Version           string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Goals             string `protobuf:"bytes,2,opt,name=goals" json:"goals,omitempty"`
	Pom               string `protobuf:"bytes,3,opt,name=pom" json:"pom,omitempty"`
	Properties        string `protobuf:"bytes,4,opt,name=properties" json:"properties,omitempty"`
	Jvmopts           string `protobuf:"bytes,5,opt,name=jvmopts" json:"jvmopts,omitempty"`
	SettingFile       string `protobuf:"bytes,6,opt,name=settingFile" json:"settingFile,omitempty"`
	GlobalSettingFile string `protobuf:"bytes,7,opt,name=globalSettingFile" json:"globalSettingFile,omitempty"`
}

func (m *Maven) Reset()                    { *m = Maven{} }
func (m *Maven) String() string            { return proto.CompactTextString(m) }
func (*Maven) ProtoMessage()               {}
func (*Maven) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Job)(nil), "configdata.Job")
	proto.RegisterType((*CodeManager)(nil), "configdata.CodeManager")
	proto.RegisterType((*BuildManager)(nil), "configdata.BuildManager")
	proto.RegisterType((*Git)(nil), "configdata.Git")
	proto.RegisterType((*Repo)(nil), "configdata.Repo")
	proto.RegisterType((*GitAdvanced)(nil), "configdata.GitAdvanced")
	proto.RegisterType((*Ant)(nil), "configdata.Ant")
	proto.RegisterType((*Maven)(nil), "configdata.Maven")
	proto.RegisterEnum("configdata.CodeManager_Kind", CodeManager_Kind_name, CodeManager_Kind_value)
	proto.RegisterEnum("configdata.BuildManager_Kind", BuildManager_Kind_name, BuildManager_Kind_value)
}

func init() { proto.RegisterFile("configData.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 651 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x94, 0xcf, 0x6e, 0xd4, 0x3e,
	0x10, 0xc7, 0x7f, 0xd9, 0xec, 0xdf, 0xd9, 0xfd, 0x95, 0xad, 0x41, 0x34, 0xa0, 0x82, 0x56, 0x51,
	0x0f, 0x3d, 0xc0, 0x82, 0x5a, 0x38, 0x20, 0xb8, 0x2c, 0xdb, 0x52, 0x95, 0xaa, 0x8b, 0x14, 0xaa,
	0xde, 0x9d, 0x64, 0x9a, 0xba, 0x24, 0x76, 0xe4, 0x78, 0xa3, 0xe5, 0x21, 0x38, 0xf1, 0x1e, 0xbc,
	0x07, 0x67, 0x5e, 0x08, 0xc5, 0xeb, 0x6d, 0xdc, 0xbf, 0xdc, 0x3c, 0xdf, 0xf9, 0x8c, 0xfd, 0xb5,
	0x27, 0x13, 0x18, 0x46, 0x82, 0x9f, 0xb1, 0x64, 0x8f, 0x2a, 0x3a, 0xce, 0xa5, 0x50, 0x82, 0xc0,
	0x52, 0x89, 0xa9, 0xa2, 0xfe, 0x2f, 0x17, 0xdc, 0xcf, 0x22, 0x24, 0x6b, 0xd0, 0x60, 0xb1, 0xe7,
	0x8c, 0x9c, 0xed, 0x5e, 0xd0, 0x60, 0x31, 0xf1, 0x61, 0xc0, 0x71, 0xa1, 0xf6, 0x17, 0x18, 0x9d,
	0xb0, 0x0c, 0xbd, 0x86, 0xce, 0x5c, 0xd1, 0xc8, 0x73, 0x80, 0x8b, 0xf8, 0xdb, 0x29, 0xca, 0x82,
	0x09, 0xee, 0xb9, 0x9a, 0xb0, 0x14, 0x32, 0x82, 0x7e, 0x38, 0x67, 0x69, 0x7c, 0x98, 0x25, 0xd3,
	0x2c, 0xf6, 0x9a, 0x1a, 0xb0, 0xa5, 0x6a, 0x87, 0x7c, 0x5e, 0x9c, 0x1b, 0xa0, 0xb5, 0xdc, 0xa1,
	0x56, 0xc8, 0x16, 0xfc, 0x1f, 0xcd, 0xa5, 0x44, 0xae, 0x66, 0xf3, 0x2c, 0x44, 0xe9, 0x75, 0x46,
	0xce, 0x76, 0x2b, 0xb8, 0x2a, 0x92, 0xd7, 0xf0, 0x30, 0xa3, 0x8b, 0xca, 0xd6, 0x5c, 0x31, 0xc1,
	0x03, 0x8c, 0x84, 0x8c, 0x0b, 0xaf, 0xab, 0xd9, 0xdb, 0x52, 0x95, 0xb3, 0x8c, 0x2e, 0x8e, 0x10,
	0xf3, 0x3d, 0xfa, 0xbd, 0xf0, 0x7a, 0x9a, 0xb4, 0x25, 0x7d, 0x37, 0x11, 0x06, 0x98, 0x89, 0x12,
	0x63, 0x0f, 0x34, 0x60, 0x29, 0xe4, 0x1d, 0xf4, 0x23, 0x11, 0xe3, 0x31, 0xe5, 0x34, 0x41, 0xe9,
	0xf5, 0x47, 0xce, 0x76, 0x7f, 0x67, 0x63, 0x5c, 0xbf, 0xec, 0x78, 0x5a, 0xa7, 0x03, 0x9b, 0x25,
	0x1f, 0x60, 0xa0, 0xdf, 0x60, 0x55, 0x3b, 0xd0, 0xb5, 0x9e, 0x5d, 0xfb, 0xd1, 0xca, 0x07, 0x57,
	0x68, 0xff, 0x87, 0x03, 0x7d, 0x6b, 0x6b, 0xf2, 0x06, 0xda, 0x05, 0xa6, 0x18, 0x29, 0xdd, 0xbc,
	0xb5, 0x9d, 0xcd, 0x3b, 0x3c, 0x8c, 0x8f, 0x18, 0x8f, 0x03, 0xc3, 0x92, 0x97, 0xd0, 0x4b, 0x98,
	0x9a, 0x6a, 0x52, 0xf7, 0xb6, 0xbf, 0xf3, 0xc0, 0x2e, 0x3c, 0x60, 0x2a, 0xa8, 0x09, 0xff, 0x09,
	0x34, 0xab, 0x72, 0xd2, 0x85, 0xe6, 0xec, 0xcb, 0x6c, 0x7f, 0xf8, 0x1f, 0xe9, 0x80, 0x7b, 0x70,
	0x78, 0x32, 0x74, 0xfc, 0xdf, 0x0e, 0x0c, 0x6c, 0xbb, 0xe4, 0xed, 0x35, 0x43, 0xcf, 0xee, 0xba,
	0xd8, 0x0d, 0x47, 0x94, 0xdf, 0xe3, 0x68, 0xc2, 0x55, 0x50, 0x13, 0xe4, 0x15, 0xf4, 0xb2, 0x92,
	0x1b, 0xdc, 0xd5, 0xf8, 0xba, 0x8d, 0x1f, 0xd3, 0x12, 0x79, 0x50, 0x33, 0xbe, 0x7f, 0xdb, 0x15,
	0x26, 0xb3, 0x93, 0xa1, 0x53, 0x2d, 0x8e, 0x4f, 0x67, 0xc3, 0x86, 0x3f, 0x05, 0xf7, 0x80, 0x29,
	0xf2, 0x18, 0xda, 0xa1, 0xa4, 0x3c, 0x3a, 0x37, 0xf3, 0x60, 0x22, 0xb2, 0x05, 0x4d, 0x89, 0xb9,
	0x30, 0xee, 0x86, 0xf6, 0x71, 0x01, 0xe6, 0x22, 0xd0, 0x59, 0x5f, 0x40, 0xb3, 0x8a, 0xc8, 0x10,
	0xdc, 0xb9, 0x4c, 0xcd, 0x16, 0xd5, 0xb2, 0xfa, 0xea, 0x22, 0x89, 0x31, 0x72, 0xc5, 0x68, 0x5a,
	0x98, 0x91, 0xb2, 0x25, 0xb2, 0x0b, 0x5d, 0x1a, 0x97, 0x94, 0x47, 0x18, 0x9b, 0x4b, 0x6d, 0x5c,
	0xeb, 0xca, 0xc4, 0xa4, 0x83, 0x4b, 0xd0, 0x7f, 0x0f, 0x7d, 0x2b, 0x41, 0x08, 0x34, 0x39, 0xcd,
	0xd0, 0x1c, 0xac, 0xd7, 0xc4, 0x83, 0x8e, 0xc4, 0xb3, 0x22, 0xc7, 0xc8, 0x9c, 0xba, 0x0a, 0xfd,
	0x9f, 0x0e, 0xb8, 0x13, 0xae, 0x2a, 0xa2, 0x34, 0x83, 0xbc, 0x2c, 0x5c, 0x85, 0x55, 0x46, 0x51,
	0x99, 0xa0, 0x5a, 0x39, 0x5e, 0x85, 0x64, 0x13, 0x7a, 0xfa, 0xd3, 0xfc, 0xc4, 0x52, 0x34, 0xe3,
	0x5f, 0x0b, 0x7a, 0xb6, 0xa5, 0xc8, 0x51, 0x2a, 0x86, 0x85, 0x19, 0x7e, 0x4b, 0x21, 0x4f, 0xa1,
	0x7b, 0x41, 0x4b, 0x2a, 0x72, 0x55, 0x98, 0xc9, 0xbf, 0x8c, 0xfd, 0x3f, 0x0e, 0xb4, 0x74, 0x07,
	0xef, 0xf1, 0xf5, 0x08, 0x5a, 0x89, 0xa8, 0xdf, 0x71, 0x19, 0x54, 0xaf, 0x9e, 0x8b, 0xcc, 0xb8,
	0xa9, 0x96, 0xff, 0xf4, 0xe1, 0x41, 0xe7, 0xa2, 0xcc, 0x2c, 0x1b, 0xab, 0xb0, 0xea, 0x57, 0x81,
	0x4a, 0x31, 0x9e, 0xe8, 0x1b, 0xb6, 0x97, 0xfd, 0xb2, 0x24, 0xf2, 0x02, 0xd6, 0x93, 0x54, 0x84,
	0x34, 0xfd, 0x6a, 0x71, 0x1d, 0xcd, 0xdd, 0x4c, 0x84, 0x6d, 0xfd, 0xfb, 0xdd, 0xfd, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xe3, 0x6f, 0x92, 0x9c, 0x92, 0x05, 0x00, 0x00,
}
