// Code generated by protoc-gen-go.
// source: configData.proto
// DO NOT EDIT!

/*
Package configdata is a generated protocol buffer package.

It is generated from these files:
	configData.proto

It has these top-level messages:
	Job
	ImgManager
	CodeManager
	BuildManager
	Git
	Repo
	GitAdvanced
	Ant
	Maven
*/
package configdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CodeManager_Kind int32

const (
	CodeManager_NONE CodeManager_Kind = 0
	CodeManager_GIT  CodeManager_Kind = 1
)

var CodeManager_Kind_name = map[int32]string{
	0: "NONE",
	1: "GIT",
}
var CodeManager_Kind_value = map[string]int32{
	"NONE": 0,
	"GIT":  1,
}

func (x CodeManager_Kind) String() string {
	return proto.EnumName(CodeManager_Kind_name, int32(x))
}
func (CodeManager_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type BuildManager_Kind int32

const (
	BuildManager_NONE  BuildManager_Kind = 0
	BuildManager_ANT   BuildManager_Kind = 1
	BuildManager_MVN   BuildManager_Kind = 2
	BuildManager_SHELL BuildManager_Kind = 3
)

var BuildManager_Kind_name = map[int32]string{
	0: "NONE",
	1: "ANT",
	2: "MVN",
	3: "SHELL",
}
var BuildManager_Kind_value = map[string]int32{
	"NONE":  0,
	"ANT":   1,
	"MVN":   2,
	"SHELL": 3,
}

func (x BuildManager_Kind) String() string {
	return proto.EnumName(BuildManager_Kind_name, int32(x))
}
func (BuildManager_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Job struct {
	Id                  string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	JdkVersion          string        `protobuf:"bytes,2,opt,name=jdkVersion" json:"jdkVersion,omitempty"`
	MaxExecutionRecords int32         `protobuf:"varint,4,opt,name=maxExecutionRecords" json:"maxExecutionRecords,omitempty"`
	MaxKeepDays         int32         `protobuf:"varint,5,opt,name=maxKeepDays" json:"maxKeepDays,omitempty"`
	CodeManager         *CodeManager  `protobuf:"bytes,6,opt,name=codeManager" json:"codeManager,omitempty"`
	BuildManager        *BuildManager `protobuf:"bytes,7,opt,name=buildManager" json:"buildManager,omitempty"`
	ImgManager          *ImgManager   `protobuf:"bytes,8,opt,name=imgManager" json:"imgManager,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetCodeManager() *CodeManager {
	if m != nil {
		return m.CodeManager
	}
	return nil
}

func (m *Job) GetBuildManager() *BuildManager {
	if m != nil {
		return m.BuildManager
	}
	return nil
}

func (m *Job) GetImgManager() *ImgManager {
	if m != nil {
		return m.ImgManager
	}
	return nil
}

type ImgManager struct {
	DockerFileContent string `protobuf:"bytes,1,opt,name=dockerFileContent" json:"dockerFileContent,omitempty"`
	DockerFile        string `protobuf:"bytes,2,opt,name=dockerFile" json:"dockerFile,omitempty"`
	ImgName           string `protobuf:"bytes,3,opt,name=imgName" json:"imgName,omitempty"`
}

func (m *ImgManager) Reset()                    { *m = ImgManager{} }
func (m *ImgManager) String() string            { return proto.CompactTextString(m) }
func (*ImgManager) ProtoMessage()               {}
func (*ImgManager) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CodeManager struct {
	Select    CodeManager_Kind `protobuf:"varint,1,opt,name=select,enum=configdata.CodeManager_Kind" json:"select,omitempty"`
	GitConfig *Git             `protobuf:"bytes,2,opt,name=gitConfig" json:"gitConfig,omitempty"`
}

func (m *CodeManager) Reset()                    { *m = CodeManager{} }
func (m *CodeManager) String() string            { return proto.CompactTextString(m) }
func (*CodeManager) ProtoMessage()               {}
func (*CodeManager) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CodeManager) GetGitConfig() *Git {
	if m != nil {
		return m.GitConfig
	}
	return nil
}

type BuildManager struct {
	SeqNo     []BuildManager_Kind `protobuf:"varint,1,rep,packed,name=seqNo,enum=configdata.BuildManager_Kind" json:"seqNo,omitempty"`
	Cmd       []string            `protobuf:"bytes,2,rep,name=cmd" json:"cmd,omitempty"`
	AntConfig []*Ant              `protobuf:"bytes,3,rep,name=antConfig" json:"antConfig,omitempty"`
	MvnConfig []*Maven            `protobuf:"bytes,4,rep,name=mvnConfig" json:"mvnConfig,omitempty"`
}

func (m *BuildManager) Reset()                    { *m = BuildManager{} }
func (m *BuildManager) String() string            { return proto.CompactTextString(m) }
func (*BuildManager) ProtoMessage()               {}
func (*BuildManager) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BuildManager) GetAntConfig() []*Ant {
	if m != nil {
		return m.AntConfig
	}
	return nil
}

func (m *BuildManager) GetMvnConfig() []*Maven {
	if m != nil {
		return m.MvnConfig
	}
	return nil
}

type Git struct {
	Branch string `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Repo   *Repo  `protobuf:"bytes,2,opt,name=repo" json:"repo,omitempty"`
}

func (m *Git) Reset()                    { *m = Git{} }
func (m *Git) String() string            { return proto.CompactTextString(m) }
func (*Git) ProtoMessage()               {}
func (*Git) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Git) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

type Repo struct {
	Url         string       `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Credentials string       `protobuf:"bytes,2,opt,name=credentials" json:"credentials,omitempty"`
	Advanced    *GitAdvanced `protobuf:"bytes,3,opt,name=advanced" json:"advanced,omitempty"`
}

func (m *Repo) Reset()                    { *m = Repo{} }
func (m *Repo) String() string            { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()               {}
func (*Repo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Repo) GetAdvanced() *GitAdvanced {
	if m != nil {
		return m.Advanced
	}
	return nil
}

type GitAdvanced struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Refspec string `protobuf:"bytes,2,opt,name=refspec" json:"refspec,omitempty"`
}

func (m *GitAdvanced) Reset()                    { *m = GitAdvanced{} }
func (m *GitAdvanced) String() string            { return proto.CompactTextString(m) }
func (*GitAdvanced) ProtoMessage()               {}
func (*GitAdvanced) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Ant struct {
	Version    string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Targets    string `protobuf:"bytes,2,opt,name=targets" json:"targets,omitempty"`
	BuildFile  string `protobuf:"bytes,3,opt,name=buildFile" json:"buildFile,omitempty"`
	Properties string `protobuf:"bytes,4,opt,name=properties" json:"properties,omitempty"`
	Javaopts   string `protobuf:"bytes,5,opt,name=javaopts" json:"javaopts,omitempty"`
}

func (m *Ant) Reset()                    { *m = Ant{} }
func (m *Ant) String() string            { return proto.CompactTextString(m) }
func (*Ant) ProtoMessage()               {}
func (*Ant) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Maven struct {
	Version           string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Goals             string `protobuf:"bytes,2,opt,name=goals" json:"goals,omitempty"`
	Pom               string `protobuf:"bytes,3,opt,name=pom" json:"pom,omitempty"`
	Properties        string `protobuf:"bytes,4,opt,name=properties" json:"properties,omitempty"`
	Jvmopts           string `protobuf:"bytes,5,opt,name=jvmopts" json:"jvmopts,omitempty"`
	SettingFile       string `protobuf:"bytes,6,opt,name=settingFile" json:"settingFile,omitempty"`
	GlobalSettingFile string `protobuf:"bytes,7,opt,name=globalSettingFile" json:"globalSettingFile,omitempty"`
}

func (m *Maven) Reset()                    { *m = Maven{} }
func (m *Maven) String() string            { return proto.CompactTextString(m) }
func (*Maven) ProtoMessage()               {}
func (*Maven) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*Job)(nil), "configdata.Job")
	proto.RegisterType((*ImgManager)(nil), "configdata.ImgManager")
	proto.RegisterType((*CodeManager)(nil), "configdata.CodeManager")
	proto.RegisterType((*BuildManager)(nil), "configdata.BuildManager")
	proto.RegisterType((*Git)(nil), "configdata.Git")
	proto.RegisterType((*Repo)(nil), "configdata.Repo")
	proto.RegisterType((*GitAdvanced)(nil), "configdata.GitAdvanced")
	proto.RegisterType((*Ant)(nil), "configdata.Ant")
	proto.RegisterType((*Maven)(nil), "configdata.Maven")
	proto.RegisterEnum("configdata.CodeManager_Kind", CodeManager_Kind_name, CodeManager_Kind_value)
	proto.RegisterEnum("configdata.BuildManager_Kind", BuildManager_Kind_name, BuildManager_Kind_value)
}

func init() { proto.RegisterFile("configData.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 685 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0xd4, 0x3a,
	0x10, 0x3e, 0xd9, 0x64, 0x7f, 0x32, 0x5b, 0xf5, 0xa4, 0x3e, 0x47, 0x3d, 0x39, 0xa8, 0xa0, 0x28,
	0xe2, 0x62, 0x2f, 0xe8, 0x82, 0xb6, 0x08, 0x09, 0xc1, 0xcd, 0xb2, 0x2d, 0x4b, 0x69, 0xbb, 0x48,
	0x6e, 0xd5, 0x7b, 0x6f, 0xe2, 0x06, 0xb7, 0x89, 0x1d, 0x12, 0x77, 0x55, 0x1e, 0x82, 0x2b, 0xde,
	0x86, 0xd7, 0xe0, 0x15, 0x78, 0x10, 0x64, 0x27, 0x69, 0x4c, 0x7f, 0xe0, 0xce, 0xf3, 0x7d, 0xdf,
	0xc4, 0x5f, 0x66, 0xc6, 0x03, 0x5e, 0x24, 0xf8, 0x19, 0x4b, 0x76, 0x89, 0x24, 0xe3, 0xbc, 0x10,
	0x52, 0x20, 0xa8, 0x90, 0x98, 0x48, 0x12, 0x7e, 0xeb, 0x80, 0xfd, 0x5e, 0x2c, 0xd1, 0x3a, 0x74,
	0x58, 0xec, 0x5b, 0x81, 0x35, 0x72, 0x71, 0x87, 0xc5, 0xe8, 0x11, 0xc0, 0x79, 0x7c, 0x71, 0x4a,
	0x8b, 0x92, 0x09, 0xee, 0x77, 0x34, 0x6e, 0x20, 0xe8, 0x19, 0xfc, 0x93, 0x91, 0xab, 0xbd, 0x2b,
	0x1a, 0x5d, 0x4a, 0x26, 0x38, 0xa6, 0x91, 0x28, 0xe2, 0xd2, 0x77, 0x02, 0x6b, 0xd4, 0xc5, 0x77,
	0x51, 0x28, 0x80, 0x61, 0x46, 0xae, 0x0e, 0x28, 0xcd, 0x77, 0xc9, 0xe7, 0xd2, 0xef, 0x6a, 0xa5,
	0x09, 0xa1, 0x97, 0x30, 0x8c, 0x44, 0x4c, 0x8f, 0x08, 0x27, 0x09, 0x2d, 0xfc, 0x5e, 0x60, 0x8d,
	0x86, 0x93, 0xff, 0xc6, 0xad, 0xdb, 0xf1, 0xac, 0xa5, 0xb1, 0xa9, 0x45, 0xaf, 0x61, 0x6d, 0x79,
	0xc9, 0xd2, 0xb8, 0xc9, 0xed, 0xeb, 0x5c, 0xdf, 0xcc, 0x7d, 0x63, 0xf0, 0xf8, 0x17, 0x35, 0x7a,
	0x01, 0xc0, 0xb2, 0xa4, 0xc9, 0x1d, 0xe8, 0xdc, 0x4d, 0x33, 0x77, 0xff, 0x9a, 0xc5, 0x86, 0x32,
	0x94, 0x00, 0x2d, 0x83, 0x9e, 0xc0, 0x46, 0x2c, 0xa2, 0x0b, 0x5a, 0xbc, 0x65, 0x29, 0x9d, 0x09,
	0x2e, 0x29, 0x97, 0x75, 0x45, 0x6f, 0x13, 0xaa, 0xc0, 0x2d, 0xd8, 0x14, 0xb8, 0x45, 0x90, 0x0f,
	0x7d, 0x96, 0x25, 0x0b, 0x92, 0x51, 0xdf, 0xd6, 0x64, 0x13, 0x86, 0x5f, 0x2c, 0x18, 0x1a, 0x85,
	0x40, 0xcf, 0xa1, 0x57, 0xd2, 0x94, 0x46, 0xd5, 0x65, 0xeb, 0x93, 0xad, 0x7b, 0x2a, 0x36, 0x3e,
	0x60, 0x3c, 0xc6, 0xb5, 0x16, 0x6d, 0x83, 0x9b, 0x30, 0x39, 0xd3, 0x4a, 0x7d, 0xfd, 0x70, 0xf2,
	0xb7, 0x99, 0x38, 0x67, 0x12, 0xb7, 0x8a, 0xf0, 0x7f, 0x70, 0x54, 0x3a, 0x1a, 0x80, 0xb3, 0xf8,
	0xb0, 0xd8, 0xf3, 0xfe, 0x42, 0x7d, 0xb0, 0xe7, 0xfb, 0x27, 0x9e, 0x15, 0xfe, 0xb0, 0x60, 0xcd,
	0x2c, 0x2e, 0xda, 0x81, 0x6e, 0x49, 0x3f, 0x2d, 0x84, 0x6f, 0x05, 0xf6, 0x68, 0x7d, 0xf2, 0xf0,
	0xbe, 0x2e, 0x54, 0x86, 0x2a, 0x2d, 0xf2, 0xc0, 0x8e, 0xb2, 0xd8, 0xef, 0x04, 0xf6, 0xc8, 0xc5,
	0xea, 0xa8, 0x1c, 0x12, 0xde, 0x38, 0xb4, 0x03, 0xfb, 0xa6, 0xc3, 0x29, 0x97, 0xb8, 0x55, 0xa0,
	0xa7, 0xe0, 0x66, 0x2b, 0x5e, 0xcb, 0x1d, 0x2d, 0xdf, 0x30, 0xe5, 0x47, 0x64, 0x45, 0x39, 0x6e,
	0x35, 0xe1, 0xf6, 0x5d, 0xbf, 0x34, 0x5d, 0x9c, 0x78, 0x96, 0x3a, 0x1c, 0x9d, 0x2e, 0xbc, 0x0e,
	0x72, 0xa1, 0x7b, 0xfc, 0x6e, 0xef, 0xf0, 0xd0, 0xb3, 0xc3, 0x19, 0xd8, 0x73, 0x26, 0xd1, 0x26,
	0xf4, 0x96, 0x05, 0xe1, 0xd1, 0xc7, 0xba, 0xb5, 0x75, 0x84, 0x1e, 0x83, 0x53, 0xd0, 0x5c, 0xd4,
	0xa5, 0xf4, 0xcc, 0x9b, 0x31, 0xcd, 0x05, 0xd6, 0x6c, 0x28, 0xc0, 0x51, 0x91, 0xfa, 0xdb, 0xcb,
	0x22, 0xad, 0x3f, 0xa1, 0x8e, 0xea, 0x79, 0x44, 0x05, 0x8d, 0x29, 0x97, 0x8c, 0xa4, 0x65, 0x3d,
	0x10, 0x26, 0x84, 0x76, 0x60, 0x40, 0xe2, 0x15, 0xe1, 0x11, 0x8d, 0xf5, 0x48, 0xdc, 0x78, 0x1b,
	0x73, 0x26, 0xa7, 0x35, 0x8d, 0xaf, 0x85, 0xe1, 0x2b, 0x18, 0x1a, 0x04, 0x42, 0xe0, 0x70, 0x35,
	0x52, 0xd5, 0xc5, 0xfa, 0xac, 0x26, 0xad, 0xa0, 0x67, 0x65, 0x4e, 0xa3, 0xfa, 0xd6, 0x26, 0x0c,
	0xbf, 0x5a, 0x60, 0x4f, 0xb9, 0x54, 0x8a, 0x55, 0xbd, 0x09, 0xaa, 0xc4, 0x26, 0x54, 0x8c, 0x24,
	0x45, 0x42, 0x65, 0xe3, 0xb8, 0x09, 0xd1, 0x16, 0xb8, 0xfa, 0x8d, 0xe9, 0xf1, 0xae, 0x26, 0xb8,
	0x05, 0xd4, 0xf4, 0xe7, 0x85, 0xc8, 0x69, 0x21, 0x19, 0xad, 0xb6, 0x86, 0x8b, 0x0d, 0x04, 0x3d,
	0x80, 0xc1, 0x39, 0x59, 0x11, 0x91, 0xcb, 0x6a, 0x53, 0xb8, 0xf8, 0x3a, 0x0e, 0xbf, 0x5b, 0xd0,
	0xd5, 0xcd, 0xfc, 0x8d, 0xaf, 0x7f, 0xa1, 0x9b, 0x88, 0xb6, 0x8e, 0x55, 0xa0, 0xaa, 0x9e, 0x8b,
	0xac, 0x76, 0xa3, 0x8e, 0x7f, 0xf4, 0xe1, 0x43, 0xff, 0x7c, 0x95, 0x19, 0x36, 0x9a, 0x50, 0xf5,
	0xab, 0xa4, 0x52, 0x32, 0x9e, 0xe8, 0x3f, 0xec, 0x55, 0xfd, 0x32, 0x20, 0xb5, 0x0f, 0x92, 0x54,
	0x2c, 0x49, 0x7a, 0x6c, 0xe8, 0xfa, 0xd5, 0x3e, 0xb8, 0x45, 0x2c, 0x7b, 0x7a, 0x37, 0xef, 0xfc,
	0x0c, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xe2, 0xcd, 0xe6, 0xaf, 0x05, 0x00, 0x00,
}
